name: CI
on:
    push:
        branches: [ $default-branch ]
    pull_request:
permissions:
    contents: read
jobs:
    build:
        name: "Tests ${{ matrix.php-version }} ${{ matrix.dependency-versions }} deps ${{ matrix.dependency-versions }}"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
                dependency-versions: ['highest']
        steps:
            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: ${{ matrix.php-version }}

            - name: Checkout repository code
              uses: actions/checkout@v3

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v2
              with:
                  composer-options: --prefer-stable --prefer-dist --no-progress
                  dependency-versions: ${{ matrix.dependency-versions }}

            - name: Run PHPUnit tests
              run: ./vendor/bin/simple-phpunit
